### ISSUE TITLE
[BE] 이슈 추가 API 다시 구현

### ISSUE THREAD

**Issue by ghojeong** [ghojeong/issue-tracker#112]
이건 기존에 노을이 작업하던 코드가 있으므로 저는 건드리지 않고, 노을에게 전부 위임하겠습니다.
주말동안 구현해서 월요일날 추가 API 를 전부 만들었다고 프론트팀에게 전달해줍시다.

**Comment by sanhee** [comment]
기존 구현이 잘돼있어서, 
아래와 같이 요청을 보내면,  이슈등록이 정상적으로 되는 것을 확인해서 특별하게 수정을 하지 않았습니다.
```json
{
  "title": "이슈 제목2",
  "comment": "이슈 내용",
  "assigneeIds":[
      "neo",
      "san"
  ],
  "labelIds":[
    1

  ],
  "milestoneId": 1
}
```

**Comment by ghojeong** [comment]
> 기존 구현이 잘돼있어서,
> 아래와 같이 요청을 보내면, 이슈등록이 정상적으로 되는 것을 확인해서 특별하게 수정을 하지 않았습니다.

사실 알고 있었습니다.
이슈 추가 API를 dto 포함해서 손 좀 봤습니다.
기존의 assiginees 를 assigneeIds 로 바꾼거 저입니다 ㅋㅋ

이슈 수정 API 을 완성하고, 다른 API 들의 문서까지 완성해서,
월요일날 프론트 분들께 전달해주시기만 하면 됩니다.

API 문서를 최신화 하는대로, 프론트분들과 스크럼 약속을 노을이 잡아주시면 감사하겠습니다.
저도 노을이 만든 문서 구경좀 해야겠군요.
제게 POSTMAN 으로 어떻게 API 문서를 만드는지도, 노하우를 알려주시면 감사하겠습니다.
