### ISSUE TITLE
[BE] assigneIds 와 labelIds 에 빈배열이 대응되도록 예외처리하기

### ISSUE THREAD

**Issue by ghojeong** [ghojeong/issue-tracker#125]
assigneeIds : [null] -> []
labeIds : [null] -> []

**Comment by sanhee** [comment]
@ghojeong 

내일 작업 하도록 하겠습니다 :)

**Comment by ghojeong** [comment]
> 내일 작업 하도록 하겠습니다 :)

훌륭합니다!
피곤한 상태로 무리하게 작업할 바에는,
한숨자거나 재밌게 놀고 재충전한 이후에 작업하는게 낫습니다.

잠을 자러 가시다니,
한단계 성장하셨군요 노을
축하드립니다.

**Comment by sanhee** [comment]
@ghojeong 
https://github.com/ghojeong/issue-tracker/pull/132 에서 해결이 된 것 같으므로

close 하도록 하겠습니다.
