### ISSUE TITLE
[BE] milestoneId 가 null 값이거나 존재하지 않을 때에 대한 예외처리

### ISSUE THREAD

**Issue by ghojeong** [ghojeong/issue-tracker#126]
지금은 milestoneId  가 반드시 존재한다고, 가정하고 있는데 마일스톤이 없을 경우도 생각해야할 것 같습니다.

**Comment by sanhee** [comment]
현재 milestoneId 필드는 없어도 이슈 생성이 잘됩니다!
나머지 옵션 assigneeIds, labelIds 에 대한 예외처리도 지금 시작하겠습니다.

```json
{
  "title": "빈 이슈 생성 제목",
  "comment": "이슈 내용",
  "milestoneId": null,
  "assigneeIds":["san","neo"],
  "labelIds":[1]
}
```

**Comment by sanhee** [comment]
앗 이미 파이로가 구현하셨던 걸 까먹었네요..ㅎㅎ..
코드보고 다시 리마인드 했습니다.
api 문서 수정하고, 해당 이슈는 close 하겠습니다.

**Comment by sanhee** [comment]
https://github.com/ghojeong/issue-tracker/pull/132#discussion_r664179340
