### ISSUE TITLE
[BE] 삭제 API 구현

### ISSUE THREAD

**Issue by ghojeong** [ghojeong/issue-tracker#130]
이번주 금요일까지의 목표를 삭제 API 의 구현으로 합시다.
반드시 **다음과 같은 순서** 로 삭제 API 를 구현할 수 있도록 해주세요.
삭제 API 를 구현할 때는 노을이 별도의 이슈로 쪼개서, 각각 다른 PR 로 올려주실 수 있도록 해주세요.
API 하나당 별도의 이슈를 만들어서 PR 을 올려주셔야 합니다. (그래야 리뷰 가능합니다.)

### 1. Comment 삭제 API

`DELETE FROM comment WHERE id=:commentId`

### 2. Label 삭제 API 

다음 순서로 2개의 쿼리가 하나의 트랜잭션으로 실행되어야 합니다.

1. `DELETE FROM issueLabel WHERE labelId=:labelId`
2. `DELETE FROM label WHERE id=:labelId`

### 3. Milestone 삭제 API

다음 순서로 2개의 쿼리가 하나의 트랜잭션으로 실행되어야 합니다.

1. `UPDATE issue SET milestoneId=null WHERE milestoneId=:milestoneId`
2. `DELETE FROM milestone WHERE id=:milestoneId`

### 4. Issue 삭제 API

다음 순서로 4개의 쿼리가 하나의 트랜잭션으로 실행되어야 합니다.

1. `DELETE FROM comment WHERE issueId=:issueId`
2. `DELETE FROM issueLabel WHERE issueId=:issueId`
3. `DELETE FROM assignee WHERE issueId=:issueId`
4. `DELETE FROM issue WHERE id=:issueId`

참고로 Assignee 삭제 API 는 Assignee 수정 API 로 충분하므로 구현하지 않겠습니다.

**Comment by ghojeong** [comment]
참고로 위는 가이드라인일 뿐이라서, 만약 노을이 더 좋은 아이디어나 구현방법이 떠오르셨다면 그리하시면 됩니다.
새벽에 가볍게 설계한거라, 틀린 쿼리나 로직이 있을 수도 있습니다.

**Comment by sanhee** [comment]
https://github.com/ghojeong/issue-tracker/issues/142

**Comment by sanhee** [comment]
https://github.com/ghojeong/issue-tracker/issues/145

**Comment by sanhee** [comment]
https://github.com/ghojeong/issue-tracker/pull/148

**Comment by sanhee** [comment]
https://github.com/ghojeong/issue-tracker/pull/150

**Comment by sanhee** [comment]
이 이슈는 해결된 것 같으니 CLOSE 하겠습니다.
