### ISSUE TITLE
[BE]  Issue 추가 시 담당자, 레이블 정보를 같이 보내도록 기능 개선

### ISSUE THREAD

**Issue by ghojeong** [ghojeong/issue-tracker#131]
[SELECT LAST_INSERT_ID()](https://github.com/ghojeong/issue-tracker/pull/120#discussion_r663479530) 를 활용해 구현하도록 하겠습니다.

결국 저도 이번주에 코딩을 하게 되는 군요.

**Comment by sanhee** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ화이팅~~!!!!!!!😁😁😁😁
