### ISSUE TITLE
[FE] MilestoneList

### ISSUE THREAD

**Issue by juddroid** [ghojeong/issue-tracker#135]
### 구현 예상
![스크린샷 2021-07-06 14 07 28](https://user-images.githubusercontent.com/70361152/124545206-9356cd00-de63-11eb-81a1-96d82baa1f73.png)

### 하위 테스크
- [x] MiliestoneList data flow
- [ ] Millestone Edit 작업
- [x] Milestone Add Post 요청

### 예상시간
4h

### 이슈
기존 LabelList Recoil에서 fetch 해서 바로 가지고 있는 방법으로는 재렌더링이 안되는 한계점을 아직 해결하지 못했기 때문에 동일한 문제 발생 예정

**Comment by ink-0** [comment]
마일스톤 POST 확인완료 이슈 닫겠습니다.
