### ISSUE TITLE
[BE] Validation 검사 적용

### ISSUE THREAD

**Issue by sanhee** [ghojeong/issue-tracker#157]
![image](https://user-images.githubusercontent.com/73760074/124746907-5cb0ad80-df5c-11eb-8464-742df9e5c72b.png)

https://github.com/ghojeong/issue-tracker/pull/144

--------
위와 같은 작업을 위해 [Hibernate Validator](http://hibernate.org/validator/) 를 한번 활용해보시기 바랍니다.

Hibernate Validator 가 에러를 던지게 하고, 이에 대한 [에러 핸들링](https://www.baeldung.com/exception-handling-for-rest-with-spring) 을 해주세요.

[Java Bean Validation Basics](https://www.baeldung.com/javax-validation)
[Validation in Spring Boot](https://www.baeldung.com/spring-boot-bean-validation)

**Comment by sanhee** [comment]
목요일에 약속이 있는 관계로

오전 혹은 밤 시간에 작업을 진행해보겠습니다!!!!

**Comment by ghojeong** [comment]
#164  이슈를 참고해서 구현해주세요

**Comment by ghojeong** [comment]
[164  PR](https://github.com/ghojeong/issue-tracker/pull/164#discussion_r665795644) 을 참고해서 구현해주세요
