### ISSUE TITLE
[BE] 배포 서버에 이슈 생성(API)시 500에러 발생

### ISSUE THREAD

**Issue by sanhee** [ghojeong/issue-tracker#161]
로컬(`backend`) 브랜치에서는 정상 작동하는데, 배포 서버에서 이슈 생성이 안되는 문제가 있습니다.

- 마일스톤id, 라벨id 없이 생성을 해도 오류가 발생함을 확인했습니다.
- 일어나시면, 서버 에러 확인해주시면 감사하겠습니다.

![image](https://user-images.githubusercontent.com/73760074/124797071-d496cc00-df8c-11eb-962d-75dd828bf200.png)

**Comment by sanhee** [comment]
조회 api 호출시에도 오류 발생합니다.
배포 서버 컴퓨터에 문제가 있는지 궁금합니다.

**Comment by sanhee** [comment]
새벽 작업이 필요한 프론트 팀에게는 로컬 서버를 통해서 작업 하는 것으로 권유 드렸습니다!

**Comment by ghojeong** [comment]
확인해봤는데, 로그인이 풀렸을 경우에 발생하는 문제같습니다.
jwt 에서 userId 값을 가져오지 못했을 때 발생하는 문제입니다.
userId 값이 null 면 401 에러를 반환하는 작업이 필요할 것 같습니다.

**Comment by ghojeong** [comment]
일단 위와 같은 문제가 생기면 재로그인 하도록 요구하면 될것 같습니다.

**Comment by ghojeong** [comment]
일단 #164  에서 500 에러가 아니라, 좀더 의미있는 에러를 반환할 수 있도록 수정해두었습니다.

**Comment by sanhee** [comment]
고생하셨습니다!!
