### ISSUE TITLE
[BE] 도메인 다이어그램 그리기

### ISSUE THREAD

**Issue by ghojeong** [ghojeong/issue-tracker#17]
오전 혹은 점심 먹고 모이는 정기 미팅에서, FE 와 IOS 팀원 분들께 [사전 정의서](https://github.com/ghojeong/issue-tracker/wiki/%EC%82%AC%EC%A0%84-%EC%A0%95%EC%9D%98%EC%84%9C)를 피드백 받은 후에,

사전 정의서에 적혀있는 용어들이 어떻게 관계 되어 있는지 간단하게 다이어그램을 그린다.
draw.io 를 사용하면 좋지만, 종이에다가 연필로 끄적끄적한것을 사진으로 찍어도 상관없다.
그린 다이어그램은 [위키 문서](https://github.com/ghojeong/issue-tracker/wiki/ERD,-%EC%97%94%ED%8B%B0%ED%8B%B0-%EA%B4%80%EA%B3%84-%EB%8B%A4%EC%9D%B4%EC%96%B4%EA%B7%B8%EB%9E%A8) 로 올린다.

명심하라! **만든 도메인 다이어그램은 언제든 삭제하고 다시 그릴 수 있다.**
즉 언제든 갈아엎고, 다시 그릴 수도 있다는 뜻이다.
그러니깐 예쁘게 그리는데 너무 시간 쏟지 말자.

**Comment by sanhee** [comment]
`예쁘게 그리는데 너무 시간 쏟지 말자. ` 명심하겠습니다 ㅎㅎ

**Comment by sanhee** [comment]
assign이나 comment 같은 부가 요소 없이 요구 사항을 크게 보고 작성해봤습니다.

![1](https://user-images.githubusercontent.com/73760074/121323249-a2bd2600-c94a-11eb-9f58-1a51cbfc4102.PNG)
![2](https://user-images.githubusercontent.com/73760074/121323261-a51f8000-c94a-11eb-8b71-cc8bcc4b5968.PNG)
![3](https://user-images.githubusercontent.com/73760074/121323267-a650ad00-c94a-11eb-866b-626615c9e8de.PNG)
![4](https://user-images.githubusercontent.com/73760074/121323275-a81a7080-c94a-11eb-89da-065b185f76b2.PNG)
![5](https://user-images.githubusercontent.com/73760074/121323282-a94b9d80-c94a-11eb-971e-02eddf1d6130.PNG)

**Comment by ghojeong** [comment]
와 저도 아이패드 갖고 싶네여

**Comment by ghojeong** [comment]
살펴 보니깐 댓글(Comment) 가 빠진것 같군요.  댓글 엔티티도 추가 부탁드립니다.

**Comment by sanhee** [comment]
`2021-06-10(목)`

> 오늘 회의 내용을 반영한 설계입니다.

| ![image](https://user-images.githubusercontent.com/73760074/121494827-0c553700-ca14-11eb-823c-591c62a197f4.png) |![image](https://user-images.githubusercontent.com/73760074/121494851-124b1800-ca14-11eb-9605-1d9191630f1b.png) | ![image](https://user-images.githubusercontent.com/73760074/121494864-15de9f00-ca14-11eb-8e07-5b51c7159f52.png) |
| :----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: |
| ![image](https://user-images.githubusercontent.com/73760074/121494898-1d05ad00-ca14-11eb-9063-0c1b8ead9079.png) | ![image](https://user-images.githubusercontent.com/73760074/121494917-21ca6100-ca14-11eb-8997-bfe9d0738f2c.png) |   ![image](https://user-images.githubusercontent.com/73760074/121494938-268f1500-ca14-11eb-800f-3c0e82c752ef.png)                                                              |
|                                                           |                                                              |                                                              |

**Comment by ghojeong** [comment]
오늘 디온이랑 이야기했는데, 노을이 말씀주신 대로, 저희가 그린 것은 ERD 라고 부르면 안되는게 맞습니다.
노을 덕분에 저도 제가 잘못 알고 있었던 것을 알게 되었네요.
위와 같은 다이어그램은 도메인 관계 다이어그램이라고 부르는게 더 적절하다고 조언 받았습니다.

노을이 말씀주신 호눅스의 생활코딩 강의 저도 보면서 공부해야할듯 싶은데,
[관계형 데이터 모델링](https://opentutorials.org/course/3883) 수업이 맞나요?
저도 노을이 알려주신 강의 똑같이 보고 싶습니다.
