### ISSUE TITLE
[BE] 포스트맨에서 이슈 생성 API 사용 시 500에러

### ISSUE THREAD

**Issue by sanhee** [ghojeong/issue-tracker#170]
포스트맨으로 요청시 500에러가 발생합니다.

## HTTP Request Header
![image](https://user-images.githubusercontent.com/73760074/124928051-3b25f380-e03a-11eb-9833-02e2330a9431.png)

```json
{
  "title": "라쿤 천재",
  "comment": "이슈 내용",
  "milestoneId": null,
  "assigneeIds":[],
  "labelIds":[]
}
```

```json
{
    "timestamp": "2021-07-08T13:09:37.145+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/api/web/issues"
}
```

- 또 null 처리가 안돼있어서, 발생한 문제 같은데, 어느 지점인지 확인할 수 없어서 난감합니다. (매번 이슈 드리는 것도 조심스럽네요..)
  - 개발 단계에서만 이라도, ExceptionHandler에 RuntimeException을 다룰 수 있게 하면 안될까요??
- 신기한 건 프론트 팀의 홈페이지에서 이슈를 작성하면 잘 동작합니다.
- backend 브랜치의 로컬 환경에서도 이슈 생성이 잘 동작하고 있습니다.
- 500 에러가 떠서 디버깅을 할 수  없어서, 이슈를 등록하게 됐습니다.

**Comment by ghojeong** [comment]
> 개발 단계에서만 이라도, ExceptionHandler에 RuntimeException을 다룰 수 있게 하면 안될까요??

알겠습니다. 허용하겠습니다.

**Comment by ghojeong** [comment]
> 신기한 건 프론트 팀의 홈페이지에서 이슈를 작성하면 잘 동작합니다.

이러면 충분한것 아닌가요? 프론트 팀에서 이슈 작성이 안된다고 이슈 제기를 한건가요?
이런 문제라면, 노을의 토큰이 잘못되었을 가능성이 큽니다.

**Comment by sanhee** [comment]
다른 분들 토큰 받아서도 진행해보았는데, 문제가 해결되지 않았어서,, 이슈를 남기게 됐습니다!
