### ISSUE TITLE
[FE] 마일스톤 편집 및 삭제

### ISSUE THREAD

**Issue by juddroid** [ghojeong/issue-tracker#172]
### 구현 결과
![스크린샷 2021-07-08 22 47 45](https://user-images.githubusercontent.com/70361152/124933112-96f27b80-e03e-11eb-9711-67395c5b826c.png)

### 하위 테스크

- [x] 마일스톤 편집
- [x] 마일스톤 삭제 

### 예상시간
3h

### 이슈
- 각각의 컴포넌트가 갖는 상태를 어떻게 효율적으로 관리할 수 있을지 고민이 됩니다.

**Comment by ink-0** [comment]
마일스톤 기능 정상작동 확인했습니다.
이슈 닫습니다.
