### ISSUE TITLE
[BE] 담당자 조회가 되지 않는 문제

### ISSUE THREAD

**Issue by sanhee** [ghojeong/issue-tracker#174]
로그인한 유저가 담당자 리스트에 출력되지 않는 문제가 있습니다.

담당자 조회 쿼리를 잘못 작성한 것으로 보입니다.

**Comment by ghojeong** [comment]
지금 근본적인 문제가 2가지 있습니다.
일단 제가 원래 의도한 assignee API 는 해당 Issue 와 연결된 사용자들을 말하는 것이었습니다.
그렇기에 Inner Join 을 허용한 것이고요.

assignee API 와는 별개로 회원가입 되어있는 전체 유저 정보를 가져오는
GET /users API 가 추가로 필요해진 것이지, 기존의 GET /assignees 가 필요없게 된 것이 아닙니다.

머지를 했다가 위화감을 느끼고 #187 에서 revert 를 했습니다.
다시 작업해주세요.

GET /assignees 를 없애는게 아니라, GET /users API 를 새로 만들어야함을 명심하세요.

**Comment by sanhee** [comment]
@ghojeong 제가 잘못 판단했군요!...

backend 브랜치 pull 땡겨서 수정 작업하도록 하겠습니다.

**Comment by ghojeong** [comment]
```GET {{ip}}/api/web/api/web/issues/{issueId}/assignees```
```GET {{ip}}/api/web/users```

이렇게 2개로 해주셔야 합니다.

기준의 assignees 를 가져올 때, 특정 issue 의 assignee 만 가져와야합니다.

다만, 프론트분들이 현재의 API 를 사용하는데 불만이 없으므로, 나아중에 작업하도록 하겠습니다.

**Comment by sanhee** [comment]
https://github.com/ghojeong/issue-tracker/issues/189
으로 새로운 이슈로 등록했습니다!

나중에 하게 되면 해당 이슈에서 처리하도록 하겠습니다!
