### ISSUE TITLE
[BE] 이슈 생성시 시간대가 한국이 아님

### ISSUE THREAD

**Issue by sanhee** [ghojeong/issue-tracker#178]
![image](https://user-images.githubusercontent.com/73760074/124963142-691b3000-e05a-11eb-885a-28ee22944be7.png)

EC2 혹은 MySQL 의 TIMEZONE을 변경해야 할 것 같습니다!!

**Comment by ghojeong** [comment]
Timezone 문제 해결했습니다.

<img width="853" alt="스크린샷 2021-07-09 오전 9 34 39" src="https://user-images.githubusercontent.com/38595650/125006390-fb422900-e098-11eb-9d86-a4548f2246b7.png">
