### ISSUE TITLE
[BE] 데이터베이스 발표자료 만들기

### ISSUE THREAD

**Issue by ghojeong** [ghojeong/issue-tracker#19]
다음 내용을 전부 슬라이드로 만들고 파이로와 검토한다.

- [ ] 검색이나 레퍼런스 없이, 댓글과 조회수 없는 기초적인 게시판 서비스의 CRUD 쿼리를 짤 수 있다.
- [ ] 키의 차이를 안다. (Natural, Artificial), (Super, Candidate, Alternate), (Primary, Foreign)
- [ ] 1정규형, 2정규형, 3정규형, BCNF 가 무엇인지 안다.
- [ ] Join 결과를 왜 Cartesian Product 라고 부르는지 설명할 수 있다.
- [ ] Persistency, Strong Consistency, Eventual Consistency 가 어떻게 다른지 안다.
- [ ] Weak Entity 와 식별 관계에 대해서 안다.
- [ ] 참조무결성 제약조건을 안다.
- [ ] 외래키 제약조건을 안다.
- [ ] 트랜잭션의 ACID 원칙에 대해서 안다.
- [ ] 트랜잭션의 Isolation Level 에서 설명할 수 있다.
- [ ] Row Store 과 Column Store 의 차이에 대해서 안다.
- [ ] RowID 가 왜 필요한지 안다.
- [ ] B+Tree 에서 Index Page 와 Data Page 가 어떻게 다른지 안다.
- [ ] Clustering Index 가 무엇인지 설명할 수 있다.
- [ ] Covering Index, Primary Index, Foreign Key Index, Unique Index, 직접 만든 Index 에 대해서 설명 가능하다.
- [ ] 쿼리 결과의 단위로 스칼라, 벡터, 레코드, 레코드 Set, 테이블 가 있다는 것을 안다.
- [ ] Optimizer 로 쿼리 플랜을 출력할 수 있다는 것을 안다. 쿼리 플랜을 분석할 줄은 모른다.
- [ ] Selectivity 가 낮으면, Index Full Scan 을 타는 경우가 있다는 걸 안다.

**Comment by ghojeong** [comment]
매일 2개씩 진행되어야 합니다. 목요일날 4개, 토요일날 4개, 다음주 화요일날 전부 되었는지 점검을 할 예정입니다.

**Comment by sanhee** [comment]
주어진 목차대로 학습을 하려 했으나...
데이터베이스 선수 지식이 부족해서 정리하기가 어려워
06/12 토요일 하루 동안 [데이터베이스 개론](http://www.yes24.com/Product/Goods/67882661) 챕터 5까지 정독했습니다.

지금까지 학습범위는 데이터베이스가 무엇인지, 데이터 모델링 개념, 키의 종류, 제약조건 까지 입니다..

**Comment by ghojeong** [comment]
저도 지금 열심히 읽는 중인데 무리하지말아요 노을
힘들면 한주 더 미루면 되죠.
전 시간 계산중인데 목요일까지는 도저히 안될것 같아서 6월 22일 화요일날 테크톡 하자고 할까 생각중입니다 ㅋㅋㅋ

**Comment by ghojeong** [comment]
내일 챕터 5까지 읽은거 서로 이야기 하는 시간 가져도 재밌겠네요 ㅋㅋㅋ
무리하지 마시고 주말인데 알람끄고 푹 늦잠도 주무시고 하세요
