### ISSUE TITLE
[FE/BE] localhost/auth 문제

### ISSUE THREAD

**Issue by juddroid** [ghojeong/issue-tracker#199]
![스크린샷 2021-07-31 22 46 33](https://user-images.githubusercontent.com/70361152/127742018-92752775-6cf5-4d3c-9b40-652fb0d07a2e.png)

새로 만든 깃헙 oauth 앱에서 localhost/auth로 로그인 시도하는 과정 중에 cors문제를 만났습니다.

![스크린샷 2021-07-31 22 48 24](https://user-images.githubusercontent.com/70361152/127742017-6afbc2bc-5bfe-4636-a865-caad00f675ff.png)

리액트 앱에서 package.json에 proxy 설정을 추가해서 cors문제를 해결해보려고 시도했어요.

![스크린샷 2021-07-31 22 50 12](https://user-images.githubusercontent.com/70361152/127742015-f30a112b-09eb-4548-8881-c23dc6c0f77d.png)

1. 요청 주소
- 현제 오류가 나는 요청 url이 `http://localhost:3000/localhost/auth` 이러면 프록시 설정이 적용이 안된건가요? 
- 네트워크 탭 상에서는 cors문제가 사라졌습니다.
- package.json 프록시의 밸류로 배포 url 주소를 적었고, 요청 url은 `localhost/auth` 이렇게 적었습니다.

2. 포스트맨 확인
- 포스트맨까지 확인해보고 말씀드리고 싶었는데,
- 포스트맨에서 auth를 확인해 볼 수 있는 메뉴가 없어진 것 같은데, 개발 중에 확인해 볼 수 있는 방법이 있을까요?

3. 이미 한 번 확인해 주신 부분인데 테스트를 못해보고 있다가 이제서야 해보고 문제가 해결 안되는 것 같아서 다시 질문드려요 ㅠ

**Comment by ghojeong** [comment]
내일 같이 화상통화해보죠

**Comment by juddroid** [comment]
감사합니다. 이슈 닫겠습니다 :)
