### ISSUE TITLE
[BE] redis 6379 포트를 15552 포트로 변경

### ISSUE THREAD

**Issue by sanhee** [ghojeong/issue-tracker#26]
![image](https://user-images.githubusercontent.com/73760074/121314851-bcf30600-c942-11eb-962a-0de2f85d8029.png)

기존 `6379` 포트 -> `15552` 포트로 변경

**Comment by ghojeong** [comment]
@sanhee 
내일 오후 3시 정기 미팅 진행할 때,
git pull 을 하고 나서 export SPRING_REDIS_PORT="6379" 를 `15552` 로 바꾸어야 함을 안내해주셔야 합니다.
