### ISSUE TITLE
[BE] JWT 담는 정보에 프로필 이미지 경로 추가

### ISSUE THREAD

**Issue by sanhee** [ghojeong/issue-tracker#32]
- private한 정보를 제거한다.
- profile image url 을 제공한다.
- 오후 3시에 깃허브 로그인으로 통일을 제안해보자 (회원가입 기능 검토)

**Comment by ghojeong** [comment]
오늘 아침에 노을이 주신 질문들의 깊이를 생각해보니. 이 이슈는 노을에게 믿고 맡겨도 되겠다는 판단을 하였습니다.

대충 다음과 같은 흐름으로 일을 처리해주세요.

1. 오늘 3시 회의에서 ERD 문서 의 피드백을 받는다.
2. 프론트가 ERD 에 합의하면, User 엔티티에서 어떤 정보를 jwt 에 담을 지 논의한다.
3. 오후 3시 회의를 끝낸다.
4. 노을 본인만의 GitHub OAuth 앱을 만들어서, GITHUB_CLIENT_ID 와 GITHUB_CLIENT_SECRET 을 교체한다. GITHUB_WEB_* 과 GITHUB_IOS_* 은 건드리지 않는다.
5. 합의한 ERD 대로 `docker/db/initdb/1_schema.sql` 에서 **User 테이블을** ERD 에 나온대로 수정한다. 다른 테이블들은 미리 하지 않는다.
6. User 테이블의 정보들을 가져올 수 있도록, 노을의 OAuth 앱의 scope 를 수정한다.
7. `domain/User`, `domain/Auth`, `dto/UserDto` 를 수정한다.
8. jwt 에 무엇을 담을지 합의한 대로, `util/JwtUtil.java` 의 내용을 수정한다.


화이팅입니다. 노을.
내일까지 완성해야지 프론트와의 로그인 기능을 합쳐서 완성할 수 있으니깐,
오늘 저녁의 DB 중간점검은 제 시간에 못하셔도 괜찮습니다.
