### ISSUE TITLE
[BE] 목업 API 구현

### ISSUE THREAD

**Issue by sanhee** [ghojeong/issue-tracker#41]
--------------------------------------

### Service: `컨트롤러`에서 전달해준 `RequsetDTO`를 `Repository`에 `Domain` 객체로 변환해서 전달 후, `Repostirory`가 반환한 `Domain` 객체를 다시 ResonponseDTO로 가공해서 `Controller`에 전달
------------------------------------------------------ (✂분리) ----------------------------------------------------------------------------
### Repository: `DB` 데이터를 가져와서 `Domain` 객체 생성

<BR>
<BR>

* ✨ Repository는 `DTO`의 존재를 몰라야 한다 ❗❗❗

--------------------------------------
* 상세한 구현 목록은 구현하면서 수정

- [x]  Issue
- [x]  Milestone
- [x]  Label
- [x]  Comment

-----------------------------------------

**Comment by ghojeong** [comment]
`GET /milestones` -> `List<MileStone>`

`GET /milestones/{milestone_id}` -> MileStone
이 MileStone 객체 안에 issue 리스트 `List<IssueDto>`가 들어있는데, 

`GET /issues?milestone=""&writer=""&created`   -> `List<IssueDto>`

필터 조건 혹은 검색 조건들은 전부 QueryString 으로

`GET /issues/{issue_id}`

`GET /issues/{issue_id}/comments`


"합치는 건 쉬운데, 쪼개는 건 어렵다!"
보통 쪼개는데 실패해서, if 떡칠, 그러니깐 일단 나중에 리뷰받고 합치는 걸로 하자!
리뷰받고 쪼갤려고 하면, 전면적인 리팩토링을 해야한다!

**Comment by ghojeong** [comment]
GET /issues

에서 open 과 closed 가 존재하지 않거나, 이상한 값이라면
default 로 open 과 closed 이슈를 모두 다 반환한다.

**Comment by ghojeong** [comment]
POST, PUT, DELETE API 는 별도의 이슈에서 만들예정입니다.
일단 GET 부터 전부 만들어주세요

**Comment by sanhee** [comment]
네..알겠습니다!..

**Comment by sanhee** [comment]
[API 문서](https://documenter.getpostman.com/view/14857650/TzeWHoES) 포스트맨에 임시로 정리 해두었습니다.
