### ISSUE TITLE
[BE] 자바 코딩 컨벤션 작성하기

### ISSUE THREAD

**Issue by ghojeong** [ghojeong/issue-tracker#48]
오늘 저와 이야기 나눈 것을 위키 문서로 작성해 주세요.
왜 해당 컨벤션이 필요한지에 대한 이유도 같이 작성해주세요.

1. domain 과 repository 는 dto 를 import 해서는 안된다.
2. 생성자 안에는 로직이 들어가서는 안된다. [참고](https://steady-coding.tistory.com/396)

**Comment by ghojeong** [comment]
생성시 넣게 되는 로직 2가지

1. 데이터 추출 혹은 변환
2. 데이터 validation: 유효성 검사

-> 생성자에게 넣는 개발자
-> 이럴 경우 생성자는 생성만 하게 하고,
-> 저런 로직들은 별도의 메서드로 분리해야한다!

SRP: Single Responsibility Principal

**Comment by ghojeong** [comment]
결론: 생성자는 항상 자동완성으로만 만들자!!

**Comment by sanhee** [comment]
1차 작성했습니다!

https://github.com/ghojeong/issue-tracker/wiki/[BE]-팀-컨벤션

**Comment by ghojeong** [comment]
읽고 있는 중인데 무척 훌륭합니다!
