### ISSUE TITLE
[FE] Milestone 페이지 레이아웃

### ISSUE THREAD

**Issue by juddroid** [ghojeong/issue-tracker#73]
- [x] 기본 레이아웃
- [x] 마일스톤 추가 레이아웃
- [x] 마일스톤 편집 레이아웃

**Comment by ink-0** [comment]
Milestone branch 73  오류 없는지 확인하고 `frontend` 브랜치에 머지했습니다. 
너무 완벽햇습니다!

**Comment by juddroid** [comment]
> Milestone branch 73  오류 없는지 확인하고 `frontend` 브랜치에 머지했습니다. 
> 너무 완벽햇습니다!

아 완전 감사해요. 확인해볼게요!
