### ISSUE TITLE
[BE] 사전 정의서 작성하기

### ISSUE THREAD

**Issue by ghojeong** [ghojeong/issue-tracker#8]
[웹 기획서](https://www.figma.com/proto/iOTGa5otAchVNyxqX6kjNI/FE_%EC%9D%B4%EC%8A%88%ED%8A%B8%EB%9E%98%EC%BB%A4?page-id=89%3A0&node-id=89%3A88&viewport=110%2C361%2C0.5&scaling=contain) 와 [모바일 기획서](https://docs.google.com/presentation/d/1EpuJNsLjoq7Jr2rD3JoFjOsvbw5qBZ3Sc-cmNcBQE44/edit#slide=id.p) 를 읽고,

한글 및 영어 키워드를 전부 뽑아내서 [사전 정의서](https://github.com/ghojeong/issue-tracker/wiki/%EC%82%AC%EC%A0%84-%EC%A0%95%EC%9D%98%EC%84%9C) 를 작성한다.

내일 아침 스크럼 시간에 노을에게 발표시킬 예정이다.

**Comment by sanhee** [comment]
https://github.com/ghojeong/issue-tracker/wiki/사전-정의서

작성했습니다. 확인해주세요!

WIKI 수정본이라 PR을 어떻게 해야할지 모르겠어서, 우선 코멘트라 남깁니다.

**Comment by ghojeong** [comment]
훌륭합니다. 확인해보겠습니다.
